Fix Opportunity and Applicant Page
SchoolTech-Indonesia/internpro-fe pull request #60
Opened 2024-10-21 10:59 UTC by elsamrafisptr

***note:**
- api is not applied
- minor fitur lainnya berhubungan dengan api diganti dengan mock data

2024-10-25 06:34 UTC, iqbalalayubbi commented
@elsamrafisptr I changed import style in your opportunity page, you can check it again and make sure it's work fine

2024-10-25 13:40 UTC, iqbalalayubbi requested changes

2024-10-25 13:40 UTC, iqbalalayubbi commented on src/components/QuillEditor/QuillEditor.jsx
> +      setEditorValue(value);
Actually, value of quill editor. already implemented on `handleEditorChange` function and if you wanna more detail about how get this value. You can see my **CreateInternship.jsx** file

2024-10-25 13:40 UTC, iqbalalayubbi commented on src/pages/Opportunity/libs/components/UpdateOpportunity/UpdateOpportunity.jsx
> +import { InfoCircleFilled } from "@ant-design/icons";
you can add this icon into `@/components/components`

2024-10-25 13:40 UTC, iqbalalayubbi commented on src/pages/Opportunity/libs/components/UpdateOpportunity/UpdateOpportunity.jsx
> +      modalRender={() => (
why not like this `<Modal>{children}</Modal>`. If you want remove the default button from modal component, you can change the value of `footer` prop into `false`. `<Modal open={isModalOpen} footer={false}></Modal>`

2024-10-25 13:40 UTC, iqbalalayubbi commented on src/pages/Opportunity/libs/components/UpdateOpportunity/UpdateOpportunity.jsx
> +      modalRender={() => (
If you just want it like that you can separate function for `modalRender`

2024-10-28 06:08 UTC, elsamrafisptr commented on src/components/QuillEditor/QuillEditor.jsx
> +      setEditorValue(value);
That is to get the assigned value/data, so it's only for UpdateModal, because when we are trying to update data we must look at our prev value like this:
**UpdateOpportunity.jsx**
![image](https://github.com/user-attachments/assets/11dc610e-32a3-49eb-b378-fdc56b8bf77e)
But, in your update internship there is no prev data, but you also haven't fetch it yet
![image](https://github.com/user-attachments/assets/da6a298d-5a1f-4a28-a3ec-d27e6dd13d12)

2024-10-29 06:54 UTC, iqbalalayubbi commented on src/components/QuillEditor/QuillEditor.jsx
> +      setEditorValue(value);
@elsamrafisptr I'm already implement auto fill input on update internship modal without use effect in quill editor component. Just set the initial value from your form
```
<Form          
          initialValues={{
            layout: "vertical",
            programName: selectedInternship.name,
            startDate: dayjs(selectedInternship.start_date),
            endDate: dayjs(selectedInternship.end_date),
            description: selectedInternship.description,
          }}
          validateMessages={{
            required: "*This field must be filled",
          }}
       ></Form>
```

2024-10-29 16:22 UTC, elsamrafisptr commented on src/components/QuillEditor/QuillEditor.jsx
> +      setEditorValue(value);
i have fixed it with your way above and commit it (but not layout well *different with my prev ss)
![image](https://github.com/user-attachments/assets/9db4aa25-7cb7-45f9-a413-d0e00dc560cb)

2024-11-07 03:59 UTC, merged