feat: filter partner
SchoolTech-Indonesia/internpro-fe pull request #65
Opened 2024-10-24 17:08 UTC by ArinBisa123

2024-10-25 11:31 UTC, iqbalalayubbi requested changes

2024-10-25 11:31 UTC, iqbalalayubbi commented on src/components/Logbook/SearchBar.jsx
> +        } h-[32px] border flex px-[12px] rounded-l-[6px]`}
`h-8 px-3 rounded-l-md`

2024-10-25 11:31 UTC, iqbalalayubbi commented on src/components/Logbook/SearchBar.jsx
> +      <div className="w-[32px] h-[32px] rounded-r-[6px] bg-[#1677FF] flex justify-center items-center">
use `<Flex>` component

2024-10-25 11:31 UTC, iqbalalayubbi commented on src/components/Logbook/SearchBar.jsx
> +        <SearchOutlined className="text-[16px] text-white" />
`text-base`

2024-10-25 12:33 UTC, iqbalalayubbi requested changes

2024-10-25 12:33 UTC, iqbalalayubbi commented on src/pages/LogbookMentor/LogbookMentorDashboard.jsx
> +import { Breadcrumb } from "antd";
import from `@/components/components`

2024-10-25 12:33 UTC, iqbalalayubbi commented on src/pages/LogbookMentor/LogbookMentorDashboard.jsx
> +      <div className="bg-white flex items-center justify-between py-4.5 px-10.5 rounded-lg shadow-[0px_4px_4px_0px_rgba(0,0,0,0.10)]">
prefer use `<Flex>` component

2024-10-26 03:32 UTC, iqbalalayubbi reviewed
I changed some import styles on logbook and logbook mentor. You can check it again and make sure it work fine

2024-10-27 07:52 UTC, ArinBisa123 commented
@iqbalalayubbi i already check it, everything works fine

2024-10-27 08:43 UTC, iqbalalayubbi approved these changes

2024-10-27 08:46 UTC, merged