Fix some feature in School Management
SchoolTech-Indonesia/internpro-fe pull request #67
Opened 2024-10-25 04:09 UTC by fadhilzamanN

- Fix Searching Feature using GetSchools()
- Fix Datepicker format when updating school
- setCurrentPage to 1 when searching and changing entries

2024-10-25 14:06 UTC, iqbalalayubbi requested changes

2024-10-25 14:06 UTC, iqbalalayubbi commented on src/hooks/schools/useSchools.js
> +      setTableErrorMessage("Data yang kamu cari tidak ditemukan");
is not absolutely about data not found. maybe, it can be server error, API error, or etc

2024-10-25 19:41 UTC, fadhilzamanN commented on src/hooks/schools/useSchools.js
> +      const { data, total } = response.data;
yeaa i guess the API having some issues now

2024-10-25 19:43 UTC, fadhilzamanN commented on src/hooks/schools/useSchools.js
> +      setTableErrorMessage("Data yang kamu cari tidak ditemukan");
okay, mayble later i will make the it based on the the response message

2024-11-05 01:47 UTC, iqbalalayubbi approved these changes

2024-11-05 01:47 UTC, merged