fix : user setting & edit profile
SchoolTech-Indonesia/internpro-fe pull request #82
Opened 2024-11-08 17:26 UTC by ArinBisa123

List of tasks:
1. Refactoring components
2. Create feature change password

2024-11-08 17:40 UTC, ArinBisa123 commented
Uploading Screen Recording 2024-11-09 003321.mp4…

2024-11-08 17:41 UTC, ArinBisa123 commented
https://github.com/user-attachments/assets/3b78f4fa-9d82-4bb4-b387-2e96268da50f

2024-11-09 00:40 UTC, iqbalalayubbi requested changes

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/pages/Admin/AdminDashboard.jsx
> +    {
Actually this code is unused, you can update your branch with last update from development branch

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/layouts/ProfileManagementLayout.jsx
> +import { AppRoute } from "@/enums/AppRoute";
`import { AppRoute } from "@/enums/enums";`

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/pages/Profile/ProfileManagement.jsx
> +      <div className="profile-container w-full h-[600px] bg-white rounded-md nunito p-[32px] text-black">
`p-[32px]`  = `p-8`

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +                ? "error"
this not implement realtime validation, you can user `rules` prop instead

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +          <Alert
this error just show once time, don't forget to set the `state` into `false` again

2024-11-09 00:40 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +            message="Change Password"
same like `currentPasswordError` state

2024-11-09 00:41 UTC, iqbalalayubbi commented
**Different UI**
![different](https://github.com/user-attachments/assets/bf0a90a2-5aac-47e9-8704-f3d98d06232a)

2024-11-10 05:08 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/EditPassword.jsx
> +                ? "error"
The alert will shown if the user click the submit button and then detect any error. If i implement real time validation on form, does the alert still needed since the submit button seems didnt hear me and then showing alerts ?.  I write this rules. Is this right? ` rules={[
              { required: true, message: "Please enter your new password" },
              {
                validator: (_, value) =>
                  value && !validateNewPassword(value)
                    ? Promise.reject(
                        "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character."
                      )
                    : Promise.resolve(),
              },
            ]}`

2024-11-10 06:26 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +                ? "error"
Actually, you can add regex pattern in rules prop.
```
rules={[
{ required: true, message: "Please enter your new password" },
{ pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&\-_])[A-Za-z\d@$!%*?&\-_]{8,}$/, 
message: "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character." },
]}
```

2024-11-10 12:53 UTC, iqbalalayubbi commented
There are several different with your slicing
1. the color of new password status text not change into green when criteria is valid
![Screenshot from 2024-11-10 19-41-13](https://github.com/user-attachments/assets/8cd349e0-051c-4df9-8432-a6db408d736b)

2. Error status not display on confirm password input
![Screenshot from 2024-11-10 19-45-41](https://github.com/user-attachments/assets/8bf5f1a1-2480-4ec9-846b-e76eef7516c6)

3. this modal not appear when password not correct
![Screenshot from 2024-11-10 19-45-41](https://github.com/user-attachments/assets/d6da3474-7e78-49d4-aebe-185297b04aeb)

2024-11-10 12:54 UTC, iqbalalayubbi commented
Don't forget to rename your branch into **dev-sp8-profile-management**

2024-11-10 12:58 UTC, iqbalalayubbi requested changes

2024-11-10 12:58 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +          Modal.error({
I think this error occur when confirm password doesn't match and not for server error
![image](https://github.com/user-attachments/assets/4cc178c9-2c3a-4409-9c27-2adfb8384f85)

2024-11-10 13:38 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/EditPassword.jsx
> +          Modal.error({
i think this modal only appear when server error, when confirm password doesnt match with new password it will shows error alert not this modal 
![Screenshot (244)](https://github.com/user-attachments/assets/7882776f-bf98-40bb-ae83-ae41969e7075)

2024-11-10 15:00 UTC, ArinBisa123 commented
the text " At least 6 characters, uppercase and lowercase letters, 1 number, and 1 symbol" color will change into green if the submit button is being clicked, i cannot implement to rules prop for real time validation since the rules prop should be used for validation only, and it’s not meant for styling purposes. The error or success messages should be handled by the help prop.

2024-11-10 15:12 UTC, ArinBisa123 commented
> Don't forget to rename your branch into **dev-sp8-profile-management**

i already rename branch should i open new PR from the new name branch?

2024-11-10 22:47 UTC, iqbalalayubbi commented
> > Don't forget to rename your branch into **dev-sp8-profile-management**
> 
> i already rename branch should i open new PR from the new name branch?

I think you should rename this branch from github as well and make sure your local and remote branch have the same name. Then, try to push again. If not working you can create new PR.

2024-11-10 23:51 UTC, iqbalalayubbi commented
> the text " At least 6 characters, uppercase and lowercase letters, 1 number, and 1 symbol" color will change into green if the submit button is being clicked, i cannot implement to rules prop for real time validation since the rules prop should be used for validation only, and it’s not meant for styling purposes. The error or success messages should be handled by the help prop.

You can make this validation realtime by using `onFieldsChange` prop from `Form` component. All validation can be handle from this event include your regex pattern. This example how you can handle it

```
  const [alert, setAlert] = useState({
    currentPasswordError: false,
    newPasswordError: false,
    newAndConfirmError: false,
  });

  const RULES_MESSAGE = {
    NEW_PASSWORD:
      "At least 6 characters, uppercase and lowercase letters, 1 number, and 1 symbol",
  };

  const handleFieldChange = async (changedFields) => {
    const field = changedFields[0];

    const { errors, name } = await field;

    if (name[0] === "newPassword") {
      const isNewPasswordError = errors[0] === RULES_MESSAGE.NEW_PASSWORD;
      setAlert((prev) => ({ ...prev, newPasswordError: isNewPasswordError }));
    }
  };

<Form
          onFieldsChange={handleFieldChange}
          form={form}
>
<Form.Item
            label="New Password"
            layout="vertical"
            name="newPassword"
            className="font-normal text-sm"
            help={
              <span
                className={`${
                  alert.newPasswordError ? "text-red-500" : "text-green-500"
                }`}
              >
                RULES_MESSAGE.NEW_PASSWORD
              </span>
            }
            rules={[
              { required: false, message: "Please enter your new password" },
              {
                pattern:
                  /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&\-_])[A-Za-z\d@$!%*?&\-_]{8,}$/,
                message: RULES_MESSAGE.NEW_PASSWORD,
              },
            ]}
          >
            <Input.Password
              placeholder="Enter your new password"
              iconRender={(visible) =>
                visible ? <EyeTwoTone /> : <EyeInvisibleOutlined />
              }
              onChange={handleChange}
              value={formData.newPassword}
              id="newPassword"
              name="newPassword"
              prefix={<LockOutlined />}
            />
          </Form.Item>
</Form>
```

2024-11-10 23:59 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +          Modal.error({
I think the design little bit ambiguous. Maybe you can clear it with the UI/UX team

2024-11-11 14:09 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/EditPassword.jsx
> +          Modal.error({
![Screenshot 2024-11-11 210739](https://github.com/user-attachments/assets/bae7774e-fdbb-4ae0-9ecd-8e1c1e8b40ee)
this morning i asked kak johan, and this is his answer

2024-11-11 14:13 UTC, ArinBisa123 commented
> > > Don't forget to rename your branch into **dev-sp8-profile-management**
> > 
> > 
> > i already rename branch should i open new PR from the new name branch?
> 
> I think you should rename this branch from github as well and make sure your local and remote branch have the same name. Then, try to push again. If not working you can create new PR.

las night i wrote command `git -m dev-sp8-profile-management` and then `git push origin -u dev-sp8-profile-management` are those right commands to rename branch?

2024-11-11 14:58 UTC, closed without merging