solving conflict from development at local repo
SchoolTech-Indonesia/internpro-fe pull request #83
Opened 2024-11-11 02:48 UTC by juvenslaurensiusdwitama

2024-11-11 03:48 UTC, iqbalalayubbi requested changes

2024-11-11 03:48 UTC, iqbalalayubbi commented on src/hooks/partners/usePartners.js
> +        const { data, meta } = await PartnerApi.getPartners(
If the API have multiple params you can wrap it using object destructuring, like this
`getPartners({rowsPerPage, search, etc})`

2024-11-11 03:48 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
> +import CreatePartner from "./libs/components/Modal/CreatePartner";
export your `modal` components in one file and you can simplify your `import` statement. `import {CreatePartner, DetailPartner, etc} from ./libs/components`

2024-11-11 03:48 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
> +import TablePartner from "./libs/components/Table/Table";
import in one statement 
`import {TablePartner, HeaderSection} from "./libs/components"`

2024-11-11 03:48 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
> +        <CreatePartner
create like my `showModal()` function in **InternshipDashboard.jsx**

2024-11-11 03:48 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/HeaderSection/HeaderSection.jsx
> +      <div className="flex w-full gap-4">
use `<Flex>` component

2024-11-13 00:29 UTC, iqbalalayubbi requested changes

2024-11-13 00:29 UTC, iqbalalayubbi commented on src/hooks/partners/usePartners.js
> +      async (value) =>
declare this function outside `useEffect`

2024-11-13 00:29 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
> +} from "./libs/components/index";
if file name is index.js, you can simplify like this `./libs/components`

2024-11-13 00:29 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
> +          <CancelBtn />
why use this `footer` prop, i think antd has default button and you can change the type if it doesn't fit

2024-11-13 00:29 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +      setIsModalLoading(true);
declare outside `useEffect` for this function

2024-11-13 00:29 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +            <div className="flex flex-col gap-4 px-6 pt-4 pb-8">
use `<Flex>` component

2024-11-13 00:30 UTC, iqbalalayubbi commented
If you already fix the issue, you can close the conversation

2024-11-13 09:33 UTC, iqbalalayubbi requested changes

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
> +import { useContext, useState } from "react";
`@/hooks/hooks`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +import { useContext, useEffect, useState } from "react";
`@/hooks/hooks`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +            <div className="bg-[#F0F3F7] px-8 py-6">
add the color to tailwind config

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +              <div className="flex justify-end mt-3">
`<Flex>`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/DetailDropdown.jsx
> +import { useState } from "react";
`@/hooks/hooks`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/DetailDropdown.jsx
> +    <div className="flex flex-col gap-[6px]">
`<Flex>`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/DetailDropdown.jsx
> +            <div className="flex gap-2 items-center">
`<Flex>`

2024-11-13 09:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/DetailDropdown.jsx
> +              <div className="flex">
`<Flex>`

2024-11-14 05:29 UTC, haniframadhani commented
don't merge yet until preview pdf before upload done

2024-11-14 09:01 UTC, haniframadhani commented
- [ ] stock profile picture in list mentor of the partner

2024-11-16 03:08 UTC, haniframadhani commented
just change the commit message

2024-11-17 06:29 UTC, iqbalalayubbi requested changes

2024-11-17 06:29 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
> +import { PartnerContext } from "@/context/PartnerContext";
import all context from `@/context/contexts`

2024-11-17 06:41 UTC, iqbalalayubbi commented
I test your branch on my local and i get infinite call of `getAllPartners` function
![image](https://github.com/user-attachments/assets/7c443417-5564-404c-928c-9b9cb48c1cc0)

2024-11-20 04:00 UTC, iqbalalayubbi requested changes

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/context/MentorContext.jsx
> +import useMentors from "@/hooks/mentors/useMentors";
`@/hooks/hooks`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/context/PartnerContext.jsx
> +import usePartners from "@/hooks/partners/usePartners";
`@/hooks/hooks`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/hooks/mentors/useMentors.js
> +import { MentorApi, PartnerApi } from "@/utils/axios/ApiService";
Now, you can import all API from `@/utils/utils`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/hooks/mentors/useMentors.js
> +import { debounce } from "lodash";
I'm already include this function to **utils** folder. So, you can also import from `@/utils/utils`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +import RequiredMark from "@/components/Form/RequiredMark";
import all global component from `@/components/components`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +import { MentorApi, PartnerApi } from "@/utils/axios/ApiService";
`@/utils/utils`

2024-11-20 04:00 UTC, iqbalalayubbi commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +            rules={[{ required: true, message: "This field must be filled" }]}
If message of rules is same, you can use `validateMessages` prop on `<Form>` element and it can cover all message from rules of your input  items. You can check **CreateInternship.jsx** for more detail

2024-11-20 04:05 UTC, haniframadhani commented on src/context/MentorContext.jsx
> +import useMentors from "@/hooks/mentors/useMentors";
Fix in mentor. Skip this

2024-11-20 04:06 UTC, haniframadhani commented on src/hooks/mentors/useMentors.js
> +import { MentorApi, PartnerApi } from "@/utils/axios/ApiService";
Fix in mentor. Ignore this

2024-11-20 04:06 UTC, haniframadhani commented on src/hooks/mentors/useMentors.js
> +import { MentorApi, PartnerApi } from "@/utils/axios/ApiService";
Fix in mentor. Ignore this

2024-11-20 04:06 UTC, haniframadhani commented on src/hooks/mentors/useMentors.js
> +import { debounce } from "lodash";
Fix in mentor. Ignore this

2024-11-20 04:07 UTC, haniframadhani commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +import RequiredMark from "@/components/Form/RequiredMark";
Fix in mentor. Ignore this

2024-11-20 04:07 UTC, haniframadhani commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +import { MentorApi, PartnerApi } from "@/utils/axios/ApiService";
Fix in mentor. Ignore this

2024-11-20 04:08 UTC, haniframadhani commented on src/pages/Mentor/libs/components/modal/CreateMentor.jsx
> +            rules={[{ required: true, message: "This field must be filled" }]}
Fix in mentor. Ignore this

2024-11-20 05:56 UTC, iqbalalayubbi requested changes

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/hooks/partners/usePartners.js
> +import { PartnerApi } from "@/utils/axios/ApiService";
`@/utils/utils`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/hooks/partners/usePartners.js
> +import { debounce } from "lodash";
`@/utils/utils`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/HeaderSection/HeaderSection.jsx
> +import { useContext } from "@/hooks/hooks";
`import {useEffect, useState,useContext} from "@/hooks/hooks";`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
> +import { FILE_SIZE_LIMIT_IN_BYTE, byteToMebibyte } from "../../utils";
`import {FILE_SIZE_LIMIT_IN_BYTE} from "./constants/constants"`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
> +import PdfThumbnail from "./components/PdfThumbnail";
`import PdfThumbnail from "./components/components";`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
>          rules={[{ required: true, message: "This field must be filled" }]}
If message of rules is same, you can simply declare the message at `<Form>` element using `validateMessages` prop
```
<Form       
    form={form}
    validateMessages={{
     required: "*This field must be filled",
    }} >.....</Form>
```

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +import { PartnerApi } from "@/utils/axios/ApiService";
`@/utils/utils`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +import DetailDropdown from "./components/DetailDropdown";
import your local components like this.
`import {PaginationMentors, DetailDropdown} from "./components/components"`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +import PdfViewer from "./components/PdfViewer";
`import {PdfViewer} from "./components/components"`

2024-11-20 05:56 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/PdfThumbnail.jsx
> +import { Document, Thumbnail } from "react-pdf";
include this component as global components.
`import { Document, Thumbnail } from "@/components/components";`

2024-11-20 13:33 UTC, iqbalalayubbi requested changes

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/constants/constants.js
> +export { FILE_SIZE_LIMIT_IN_BYTE } from "@/pages/Partner/libs/utils";
Don't import this constant from your **utils**, you can create new file like `DefaultPermission`

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/hooks/hooks.js
> +  createContext,
I think `createContext` isn't hook of react and it can be make sense if we move to **utils** folder

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
> +import { PartnerApi } from "@/utils/axios/ApiService";
`import { PartnerApi } from "@/utils/utils";`

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/CreatePartner.jsx
>                  <span>{byteToMebibyte(size).toFixed(2)} MB</span>
separate new function, avoid nested elements

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/DetailPartner.jsx
> +            <div className="bg-[#F0F3F7] px-8 py-6">
add the color to tailwind config

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Modal/components/PdfViewer.jsx
> +import { PartnerApi } from "@/utils/axios/ApiService";
`import { PartnerApi } from "@/utils/utils";`

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Table/Table.jsx
> +import { PartnerApi } from "@/utils/axios/ApiService";
`import { PartnerApi } from "@/utils/utils";`

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Table/Table.jsx
> +import PartnerPagination from "./Pagination";
`import PartnerPagination from "./components";`

2024-11-20 13:33 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Table/Table.jsx
> +          <Tooltip
separate new function or component

2024-11-21 03:00 UTC, haniframadhani commented on src/hooks/hooks.js
> +  createContext,
it is a react hook
[https://react.dev/reference/react/createContext](https://react.dev/reference/react/createContext)

2024-11-21 03:09 UTC, haniframadhani commented on src/pages/Partner/libs/components/Table/Table.jsx
> +import PartnerPagination from "./Pagination";
only one component and at the same lavel. i don't think it necessary

2024-11-21 23:01 UTC, iqbalalayubbi commented on src/hooks/hooks.js
> +  createContext,
I don't think so because if you refer to the docs of the react, `createContext` include as API of react not hook and usually hook in react start with prefix `use`.
![image](https://github.com/user-attachments/assets/b9585c84-1129-42a0-9d3d-676d5603b41b)

The other reason is hook only call inside the component you can't call the hooks outside the component like this
![image](https://github.com/user-attachments/assets/e2fc6b0e-ec6f-4b76-805c-af68d53b2f9a)
But, you  can call `createContext` outside of the component
![image](https://github.com/user-attachments/assets/924c6704-8ed2-461f-a15e-b1af8881afe3)

2024-11-24 02:30 UTC, iqbalalayubbi requested changes

2024-11-24 02:30 UTC, iqbalalayubbi commented on src/pages/mentor/MentorDashboard.jsx
I think this folder not used because there isn't libs folder and I get this error when running the app
![image](https://github.com/user-attachments/assets/e78231e9-8579-4392-9312-7e930c057069)

2024-11-25 01:59 UTC, haniframadhani commented
old
![Screenshot from 2024-11-25 08-52-35](https://github.com/user-attachments/assets/ec5ec471-ef0f-4af4-8883-90e44ec7a195)
new
![image](https://github.com/user-attachments/assets/6b1a55a2-d8ab-4371-a452-d6e02a6591fc)

2024-11-25 02:00 UTC, haniframadhani commented
ignore the mentor. will be fix in mentor branch

2024-11-25 22:09 UTC, iqbalalayubbi requested changes

2024-11-25 22:09 UTC, iqbalalayubbi commented on src/pages/Partner/PartnerDashboard.jsx
>            <Breadcrumb
use global `<Header />` components.

  ```
const subPages = [
    {
      title: "Partner Management",
      path: AppRoute.PARTNER_MANAGEMENT,
    },
  ];

<Header pageName="Partner Management" subPages={subPages} />
```

2024-11-26 23:42 UTC, iqbalalayubbi requested changes

2024-11-26 23:42 UTC, iqbalalayubbi commented on src/hooks/partners/usePartners.js
> +    debounceSearch(searchValue);
This function make trigger API call for the first render and i think you also call the same API at Table Partner component

2024-11-26 23:42 UTC, iqbalalayubbi commented on src/pages/Partner/libs/components/Table/Table.jsx
> +      if (error.response.status != 404) {
```
import { ErrorCode } from "@/enums/enums";

if (error.response.status != ErrorCode.NOT_FOUND) {
```

2024-11-27 23:43 UTC, iqbalalayubbi approved these changes

2024-11-27 23:44 UTC, merged