fix: real time validation form
SchoolTech-Indonesia/internpro-fe pull request #84
Opened 2024-11-11 15:14 UTC by ArinBisa123

List of task : refactoring code to implement real time validtion on new password and confirm password field

2024-11-11 15:28 UTC, ArinBisa123 commented
kurang lebih begini :cold_sweat:

https://github.com/user-attachments/assets/64ba4b61-0cb9-42ed-b1e7-30724be251b8

2024-11-12 06:55 UTC, iqbalalayubbi requested changes

2024-11-12 06:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +                validator(_, value) {
If you already declare the rules, don't use this validator because `handleFieldChange`  event already get all error from the rules.

2024-11-12 06:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditPassword.jsx
> +                  if (!value || getFieldValue("newPassword") === value) {
create new function

2024-11-12 06:55 UTC, iqbalalayubbi commented on src/utils/axios/api/Profile.js
> +        return { success: false, message: error.response.data.message };
why not using single if statement? I think it can be like this

```
try {
    
  } catch ({response}) {
    const status = response.status
    if (response){
      if (status !== ErrorCode.UNAUTHORIZED || status !==  ErrorCode.UNPROCESSABLE){
     return {
             success: false,
             message: error.response.data.message,
             errors: error.response.data.errors,
           }
        }else{

          throw new Error("An unexpected error occurred during update password.");
       }
  }
}
```

2024-11-15 08:50 UTC, ArinBisa123 commented
https://github.com/user-attachments/assets/af436b42-8950-49fb-a413-315aa7a4cb68

2024-11-15 14:55 UTC, iqbalalayubbi requested changes

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditProfile/EditProfile.jsx
> +  });
I think you don't need this state because you can directly set the actual value to the input.

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditProfile/EditProfile.jsx
> +    return regex.test(email);
definition all rule in `<Form>` element, you can create like **EditPassword.jsx** as well

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditProfile/EditProfile.jsx
> +    setFormData((prevData) => ({ ...prevData, phone }));
no need this function, if you use `<Form>` element

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditProfile/EditProfile.jsx
> +            email: formData.email,
create new function, avoid nested code

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/EditProfile/EditProfile.jsx
> +                value={formData.nip_nisn}
why not directly pass the value `profileData.nip_nisn`

2024-11-15 14:55 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +import { EditPassword } from "..";
I think if these components render as child of ShowProfile component, you should move two component depend your ShowProfile folder. So, you can import all component like this
`import {EditProfile, EditPassword} from "./components"`

and your folder structure should like this

- ShowProfile
  - components
     - EditProfile
     - EditPassword

2024-11-17 06:25 UTC, iqbalalayubbi requested changes

2024-11-17 06:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/constants/ErrorMessage.js
> +  PHONE_NUMBER: "*Please enter only 12 or 13 numbers",
`*Please enter only 12 numbers.`

2024-11-17 06:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +        content: "Failed to update data",
not same
![image](https://github.com/user-attachments/assets/fff58fa1-4333-46ee-861b-bedeb8bbaf59)

2024-11-17 06:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +    const emailRegex = /^[a-zA-Z0-9._]+@[a-z]+\.[a-z]{2,6}$/;
no need this function, you can use `form.validateFields()` function to check your form is correct or not

2024-11-17 06:26 UTC, iqbalalayubbi commented
I'm not see this confirm modal after click submit
![image](https://github.com/user-attachments/assets/cff7c1ae-7a8d-46cf-8b91-1c8f4425920d)

2024-11-18 11:44 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +    const emailRegex = /^[a-zA-Z0-9._]+@[a-z]+\.[a-z]{2,6}$/;
i still need it to control showing help message

2024-11-18 12:54 UTC, ArinBisa123 commented
> I'm not see this confirm modal after click submit ![image](https://private-user-images.githubusercontent.com/79147766/386924831-cff7c1ae-7a8d-46cf-8b91-1c8f4425920d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzAzMTMsIm5iZiI6MTczMTkzMDAxMywicGF0aCI6Ii83OTE0Nzc2Ni8zODY5MjQ4MzEtY2ZmN2MxYWUtN2E4ZC00NmNmLThiOTEtMWM4ZjQ0MjU5MjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDExNDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzlhZmU2MDc3N2UyNGVkMDI2ZTJkNWJkOWZiODlmYzEzMjkyMTY1Y2I3NGQ4ZWY0NzVjMjA4NDI0ZWI2MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KoAdQAEX5i8wCUroPDGeXIulEaJpRRCHPpAJ6W3jjbc)

upsie sorry

2024-11-18 13:40 UTC, iqbalalayubbi requested changes

2024-11-18 13:51 UTC, iqbalalayubbi commented
Your regex pattern is invalid

![image](https://github.com/user-attachments/assets/ba885b0a-6318-4d51-8426-e9d9db788276)

2024-11-18 13:54 UTC, iqbalalayubbi requested changes

2024-11-18 13:54 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +      <Form
Don't forget to use `form` prop to make sure all validation work

2024-11-19 08:26 UTC, iqbalalayubbi requested changes

2024-11-19 08:26 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +        {profileData.role === "Koordinator" ? (
why use conditional rendering?. I think both true and false statements are same

2024-11-19 08:26 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +                disabled
remove `id. type,` and `value` from your inputs. No need this props, i guess

2024-11-19 09:56 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +        {profileData.role === "Koordinator" ? (
no it dont same. If user role is Koordinator. The form field will be like this (there is no class field) 
![Screenshot 2024-11-19 165432](https://github.com/user-attachments/assets/69b920b9-f3c0-4546-8696-a6af068d10c0)
And if user role is Student. The form field will be like this (there is class field)
![Screenshot 2024-11-19 165442](https://github.com/user-attachments/assets/d0413e74-670d-4402-b524-63f56d0513b0)

2024-11-19 10:16 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +        {profileData.role === "Koordinator" ? (
Hmm i see sorry, but i think you can just make conditional rendering only for the class input field because your code is like repeated twice

2024-11-19 11:25 UTC, iqbalalayubbi requested changes

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +        <div className="card-profile_1  h-[162px] p-7 bg-secondary border-cardProfile flex-col justify-start items-start gap-2.5">
use `<Flex>` component

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +          <div className="card-content h-[88px] flex-col justify-start items-start flex gap-2">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +          <div className="card-content-header flex flex-row justify-between">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
`<Flex>`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditPassword/EditPassword.jsx
> +import { ProfileApi } from "@/utils/axios/ApiService";
Now, you can export all API from `@/utils/utils`

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/components/EditProfile/EditProfile.jsx
> +import { ProfileApi } from "@/utils/axios/ApiService";
import all API from `@/utils/utils`

2024-11-19 11:25 UTC, iqbalalayubbi commented on tailwind.config.js
don't touch this file, if you not working on this file because some values ​​are used in other files

2024-11-19 11:25 UTC, iqbalalayubbi commented on src/pages/Profile/ProfileManagement.jsx
>  import { ProfileApi } from "@/utils/axios/ApiService";
import all API from `@/utils/utils`

2024-11-19 13:45 UTC, iqbalalayubbi commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
hmm yeah your right, but the reason is about semantic element. `<Flex>` element is more meaningful than `<div>` element. Another reason is about readable code and I think we agree too prioritize antd components before using the default HTML elements.

2024-11-19 15:25 UTC, ArinBisa123 commented on src/pages/Profile/libs/components/ShowProfile/ShowProfile.jsx
> +              <div className="content flex flex-col gap-1">
siap

2024-11-19 22:17 UTC, iqbalalayubbi requested changes

2024-11-19 22:17 UTC, iqbalalayubbi commented on tailwind.config.js
Don't modify this file, if you are not working on this file

2024-11-19 22:48 UTC, ArinBisa123 commented on tailwind.config.js
i think i never modify this file tpi gk tau kenapa bisa beda gitu dri branch development maybe i didnt teliti when solve conflict while merging with branch dev

2024-11-20 03:43 UTC, iqbalalayubbi approved these changes
ACC

2024-11-20 03:43 UTC, merged