Dev activity
SchoolTech-Indonesia/internpro-fe pull request #96
Opened 2024-12-10 05:28 UTC by juvenslaurensiusdwitama

2024-12-10 05:49 UTC, iqbalalayubbi requested changes

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +import { ActivityApi } from "@/utils/axios/ApiService";
import all API from global utils folder
`@/utils/utils`

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +            console.error(err)
`no console rule` just replace with error modal

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +    console.log(activityData)
`no console rule`

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +                    <span className="text-[#00000099]">({activityData?.length? activityData.length : '0'})</span>
add this color into **tailwind.config.js**

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +            {isLoading ? <div className="h-32 m-4 flex flex-col-reverse justify-center items-center gap-3 text-slate-400">Loading... <Spin/></div>
use `<Flex>` component

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
> +import { PartnerApi } from '@/utils/axios/ApiService'
`@/utils/utils`

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
> +            .catch(err => console.error(err))
`no console`

2024-12-10 05:49 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/components/DeleteActivity.jsx
> +            console.log(response)
`no console`

2024-12-11 01:31 UTC, iqbalalayubbi requested changes

2024-12-11 01:31 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +            {isLoading ? <div className="h-32 m-4 flex flex-col-reverse justify-center items-center gap-3 text-slate-400">Loading... <Spin/></div>
use `<Flex>` component instead

2024-12-11 01:31 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
> +            .then(res => setDetailPartner(res))
prefer using `async await` and move the function to outside of `useEffect`

2024-12-11 01:31 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
>              <Flex className='justify-between p-6 border-b border-b-[#00000026] border-solid'>
instead of using `className` you can use `justify` prop from `<Flex>` component

2024-12-11 01:31 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
>              <Flex gap={8} className='justify-end py-4 px-6'>
use `justify` prop

2024-12-11 01:31 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/components/UpdateActivity.jsx
> +import { ActivityApi } from '@/utils/axios/ApiService';
import API from `@/utils/utils`

2024-12-11 02:37 UTC, juvenslaurensiusdwitama commented on src/pages/Activity/libs/components/CardActivity/components/UpdateActivity.jsx
> +import { ActivityApi } from '@/utils/axios/ApiService';
done

2024-12-11 02:39 UTC, juvenslaurensiusdwitama commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
>              <Flex gap={8} className='justify-end py-4 px-6'>
done

2024-12-11 02:40 UTC, juvenslaurensiusdwitama commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
>              <Flex className='justify-between p-6 border-b border-b-[#00000026] border-solid'>
done

2024-12-11 08:53 UTC, iqbalalayubbi requested changes

2024-12-11 08:53 UTC, iqbalalayubbi commented on src/pages/Activity/libs/components/CardActivity/CardActivity.jsx
> +            Modal.error({
import `modal` first

2024-12-11 08:53 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +                    : <Flex gap={24} vertical className="justify-center items-center h-[300px] rounded-md border-2 border-[#0000000f] border-solid">
use `justify` prop

2024-12-11 08:53 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +                        <Flex vertical className="justify-center items-center h-[300px] rounded-md border-2 border-[#0000000f] border-solid">
use `justify` prop

2024-12-11 08:53 UTC, iqbalalayubbi commented on src/pages/Activity/ActivityDashboard.jsx
> +            {isLoading ? <Flex className="h-32 m-4 flex-col-reverse justify-center items-center gap-3 text-slate-400">Loading... <Spin/></Flex>
use `justify` and `align` props

2024-12-12 13:04 UTC, iqbalalayubbi approved these changes

2024-12-12 13:04 UTC, merged